services:
  odoo:
    restart: always
    container_name: odoo-main
    build:
      context: .
    ports:
      - "8069:8069"
    command: >
      sh -c "python3 odoo-bin --addons-path=addons -d mydb --db_host=db --db-filter=.* --db_port=5432 --db_user=${DB_USER} --db_password=${DB_PASSWORD} -i base"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}


