[options]
; This is the password that allows database operations:
admin_passwd = Gl0b@lh3@lth@645
db_host = db
db_port = False
db_user = odoo
db_password = G10b3lh3alth@420
addons_path = odoo16/addons,odoo-custom-addons
